### ISSUE TITLE
Headers for sketchup files

### ISSUE THREAD

**Issue by TCMiranda** [int0x80/anti-forensics#2]
Hey! Thanks for sharing.
Can you point me how o create a header for sketchup (.skp) files?
Thanks

**Comment by int0x80** [comment]
My general blackbox method is to take a collection of the files in question (*.skp), examine the first 8-16 bytes of each file, then manually look for common patterns. Here is an example with pdf files.

```
$ find . -iname "*.pdf" -type f 2>/dev/null | while read filename; do 
  dd if="${filename}" bs=8 count=1 2>/dev/null | xxd; 
done
```

The output looks like:

```
00000000: 2550 4446 2d31 2e33                      %PDF-1.3
00000000: 2550 4446 2d31 2e34                      %PDF-1.4
00000000: 2550 4446 2d31 2e36                      %PDF-1.6
```

Based on that, I could add a signature to the scalpel config like:

```
pdf                                 y    2500000    \x25\x50\x44\x46\x2d\x31\x2e
```

It appears that scalpel after 1.90 supports regex in the config, so something like this might work:

```
pdf                                 y    2500000    %PDF-1.[0-9]
```

Note that `2500000` is an arbitrary number. You may need to increase that value if the files you want to carve are larger than this.

Additionally it's possible someone online has documented the file format with more detail or you might be able to reverse engineer an application which parses/loads .skp files to see what bytes they examine and how they are processed. This is asserting that the application does a sanity check to verify the file has a valid format. 

Lastly, please submit a pull request if you derive a robust signature. Best wishes and good luck on your file recovery (boa sorte)!

**Comment by TCMiranda** [comment]
Thank you for the detailed explanation! I really appreciate it.
Best regards!
